import type { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: 'all', label: 'All', icon: 'LayoutGrid' },
  { id: 'kitchen-appliances', label: 'Kitchen Appliances', icon: 'CookingPot' },
  { id: 'indoor-lighting', label: 'Indoor Lighting', icon: 'Lightbulb' },
  { id: 'household-cleaners', label: 'Household Cleaners', icon: 'Sparkles' },
  { id: 'mens-tshirts', label: "Men's T-Shirts", icon: 'Shirt' },
  { id: 'womens-tshirts', label: "Women's T-Shirts", icon: 'Shirt' },
  { id: 'makeup', label: 'Makeup Products', icon: 'Palette' },
  { id: 'leggings', label: 'Leggings', icon: 'PersonStanding' },
  { id: 'jewelry', label: 'Jewelry', icon: 'Gem' },
  { id: 'hair-dye', label: 'Hair Dye', icon: 'Droplets' },
  { id: 'hair-styling', label: 'Hair Styling Tools', icon: 'Wind' },
  { id: 'hair-treatment', label: 'Hair & Scalp Treatments', icon: 'HeartPulse' },
  { id: 'bodycare-men', label: 'Body-care for Men', icon: 'FlaskConical' },
  { id: 'textbooks', label: 'Textbooks', icon: 'BookOpen' },
  { id: 'toys-games', label: 'Toys & Games', icon: 'Gamepad2' },
  { id: 'earphones', label: 'Earphones & Headphones', icon: 'Headphones' },
  { id: 'perfume', label: 'Perfume', icon: 'SprayCan' },
  { id: 'stickers', label: 'Phone & Laptop Stickers', icon: 'Sticker' },
  { id: 'manicure', label: 'Manicure & Pedicure Tools', icon: 'Hand' },
  { id: 'hoodies', label: 'Hoodies & Sweatshirts', icon: 'Cloud' },
  { id: 'sunglasses', label: 'Sunglasses', icon: 'Sun' },
  { id: 'back-to-school', label: 'Back to School', icon: 'Backpack' },
  { id: 'celebrations', label: 'Celebrations', icon: 'PartyPopper' },
  { id: 'bicycles', label: 'Bicycles', icon: 'Bike' },
  { id: 'shoes', label: 'Shoes', icon: 'Footprints' },
];

export const products: Product[] = [
  // Kitchen Appliances
  { id: 'kap-01', title: 'Mellerware Kettle Cordless Glass Black 1.8L 2200W', price: 350.00, originalPrice: 388.89, description: 'Introducing the BrandMellerware Kettle, designed for efficiency and safety. With a generous 1.8-liter capacity and a sleek black finish, this high borosilicate glass kettle features a powerful 2200W concealed heating element, ensuring quick boiling. The automatic shut-off, boil-dry, and overheat protection features guarantee peace of mind, while the 360º swivel base and LED illumination light add convenience and style to your kitchen experience.', image: '/images/ka1.jpg', category: 'kitchen-appliances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'kap-02', title: 'Toaster 2-Slicess, Stainless Steel, Black and Silver, 650W', price: 289.00, originalPrice: 321.11, description: 'Introducing the Silver Toaster, a compact and efficient kitchen essential for your breakfast preparation. With a 2-slice capacity and 650W power, it offers six adjustable browning levels to perfectly toast your bread or bagels to your liking. The convenient cancel function allows you to stop the toasting process at any time, while the removable crumb tray ensures easy cleaning and maintenance. Enjoy consistent performance and stylish design in one appliance', image: '/images/ka2.jpg', category: 'kitchen-appliances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'kap-03', title: 'Russell Hobbs 500W Royal Jug Blender', price: 879.00, originalPrice: 976.67, description: 'the BrandRussell Hobbs Black Blender, featuring a 1.5-liter glass jug with a convenient grinder/mill attachment for versatile blending. With two speeds and a pulse function, you can easily control your blending tasks, while the safety lock mechanism and removable filter cap ensure secure operation. The non-slip feet provide added stability, making this blender not only efficient but also easy to clean and use in any kitchen.', image: '/images/ka3.jpg', category: 'kitchen-appliances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'kap-04', title: 'Microwave Oven 20L', price: 1349.00, originalPrice: 1498.89, description: 'Compact 20L microwave with 5 power levels', image: '/images/ka4.jpg', category: 'kitchen-appliances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'kap-05', title: 'Russell Hobbs RHEP7 Electric Pressure Cooker, Silver/Black, 6 Litre Capacity', price: 2059.00, originalPrice: 2287.78, description: 'the BrandRussell Hobbs Silver/Black Slow Cooker, designed with a generous 6-liter capacity for all your culinary needs. Ideal for preparing stews, soups, meats, and more, it features convenient reheat and keep warm modes, along with user-friendly touch button settings. The 90-minute countdown timer with a digital LED display and nine advanced safety features ensure reliable performance and peace of mind while cooking. Enjoy effortless meals with this stylish and functional kitchen essential', image: '/images/ka5.jpg', category: 'kitchen-appliances', stock: 5, special: true, rating: 0, reviews: 0 },
  

  // Plastic Water bottle & Lunch box
  { id: 'pwb-02', title: 'Curve Water Bottle 1,1lt - Green', price: 152.10, originalPrice: 169.00, description: 'Curve Water Bottle 1,1lt - Green', image: '/images/pwblb2.jpg', category: 'Plastic Water bottle & Lunch box', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'pwb-03', title: 'Hexagon Water Bottle 500ml - Teal', price: 107.10, originalPrice: 119.00, description: 'Hexagon Water Bottle 500ml - Teal', image: '/images/pwblb3.jpg', category: 'Plastic Water bottle & Lunch box', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'pwb-04', title: 'Square Food Storage 3Lt - Teal', price: 180.00, originalPrice: 200.00, description: 'Square Food Storage 3Lt - Teal', image: '/images/pwblb4.jpg', category: 'Plastic Water bottle & Lunch box', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'pwb-05', title: 'Large Marinator - Teal', price: 270.00, originalPrice: 300.00, description: 'Large Marinator - Teal', image: '/images/pwblb5.jpg', category: 'Plastic Water bottle & Lunch box', stock: 5, special: true, rating: 0, reviews: 0 },
   { id: 'pwb-05', title: '4-Color Carbonated Beverage Can Lids with Straws', price: 50.00, originalPrice: 70.00, description: 'Keep your drinks fresh and spill-free with these 4-Color Carbonated Beverage Can Lids with Straws. Each set includes either 4 or 1 multicolor lid and straw combinations that fit most standard cans, making them perfect for sparkling beverages, sodas, and canned drinks. Designed for food preservation and easy sipping, these reusable lids help maintain carbonation and prevent spills—ideal for daily use, kitchen storage, travel, camping, holidays, and special occasions like weddings. Durable and easy to clean, a practical and colorful addition to any kitchen or on-the-go essentials kit. Enjoy hassle-free, portable beverage storage and serve your drinks with style and convenience.', image: '/images/pwblb5.jpg', category: 'Plastic Water bottle & Lunch box', stock: 5, special: true, rating: 0, reviews: 0 },


  // Indoor Lighting
  { id: 'inl-01', title: 'LED Desk/Bedside Lamp', price: 129.00, originalPrice: 143.33, description: ' the Norden LED Lamp, featuring touch control and a 360-degree gooseneck for versatile lighting. With three adjustable light modes—natural, white, and warm—you can create the perfect atmosphere while reducing eye strain. This compact, portable lamp is USB rechargeable, providing over 4 hours of illumination on a single charge, and consumes just 2.5W of power for an energy-efficient solution. Ideal for any desk or bedside table, it combines modern style with eco-friendly functionality.', image: '/images/inl1.jpg', category: 'indoor-lighting', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'inl-02', title: 'Fairy Lights 10m', price: 79.00, originalPrice: 87.78, description: '100 LED Purple Christmas Fairy Lights, a 10M extendable string perfect for enhancing your holiday decorations. Featuring eight adjustable lighting modes, including steady and flash, these lights create the ideal ambiance for parties, weddings, and home decor. Designed for both indoor and outdoor use, the IP44 waterproof rating ensures durability, while the energy-efficient LED bulbs offer long-lasting performance. Easily connect multiple strings to cover larger areas, making them a versatile addition to any festive setting.', image: '/images/inl2.jpg', category: 'indoor-lighting', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'inl-03', title: 'Smart Bulb Multicolor', price: 287.00, originalPrice: 318.89, description: 'the Tapo L530E Smart Wi-Fi Light Bulb. This energy-efficient multicolor LED bulb offers 16 million shades and adjustable brightness, allowing you to create personalized lighting scenarios for any occasion. Control your lights remotely via the free Tapo app on iOS and Android, or use voice commands with Alexa and Google Assistant for hands-free convenience. With features like programmable settings, an absent mode for security, and no hub required for setup, this smart bulb seamlessly integrates into your smart home.', image: '/images/inl3.jpg', category: 'indoor-lighting', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'inl-04', title: 'Bedside Night Light', price: 290.00, originalPrice: 322.22, description: 'the Small Table Lamp, a compact and minimalist lighting solution perfect for bedrooms, living rooms, dorms, and offices. With a stylish design and warm white linen lampshade, this lamp provides soft, eye-friendly lighting that enhances any space warmth and comfort. Compatible with E27 standard bulbs (max 40W, bulb not included), it supports various bulb types and creates a cozy ambiance for reading or relaxing. Easy to install with a convenient cord switch, this lightweight lamp is ideal for adding a touch of elegance and functionality to your home.', image: '/images/inl4.jpg', category: 'indoor-lighting', stock: 5, special: true, rating: 0, reviews: 0 },

  // Household Cleaners
  { id: 'hcl-01', title: 'Multi-Surface Cleaner Mr Muscle', price: 79.00, originalPrice: 87.78, description: 'This 750 ml spray effectively cleans and disinfects various surfaces, eliminating harmful bacteria and viruses while leaving a fresh scent. Its easy-to-use trigger spray allows for hassle-free application, and it wipes off effortlessly without damaging surfaces or requiring scrubbing. Trust Mr Muscle for a reliable and efficient cleaning solution for your home.', image: '/images/hcl1.jpg', category: 'household-cleaners', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'hcl-02', title: 'Dishwashing Liquid', price: 42.00, originalPrice: 46.67, description: 'Sunlight Regular Dishwashing Liquid 750 ml', image: '/images/hcl2.jpg', category: 'household-cleaners', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'hcl-03', title: 'Laundry Detergent OMO Auto Washing 3L', price: 190.00, originalPrice: 211.11, description: 'OMO Stain Removal Auto Washing Liquid Detergent in a 3L bottle. Featuring EcoBoost technology, this liquid penetrates deep into fabrics to tackle tough stains effectively, offering unbeatable stain removal with just one capful. Made with naturally derived cleaning agents. Is tough on stains while being kinder to the planet and is suitable for all machine types. Each bottle cleans up to 40 loads, providing a convenient and efficient laundry solution without leaving any residue.', image: '/images/hcl3.jpg', category: 'household-cleaners', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'hcl-04', title: 'Disinfectant Cleaner Spray Handy Andy 500 ml', price: 60.00, originalPrice: 66.67, description: '500 ml Handy Andy Professional Disinfectant Cleaner Spray, 500 ml, is a fresh-scented, biodegradable spray designed for marble surfaces. It cleans and disinfects, removes daily kitchen dirt, and dries quickly for hygienic, safer surfaces.', image: '/images/hcl4.jpg', category: 'household-cleaners', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Men's T-Shirts
  { id: 'mts-01', title: 'White T-shirt', price: 420.00, originalPrice: 466.67, description: 'White Daniel Hechter T-shirt in a cotton-blend knit, featuring short sleeves and a clean white finish.', image: '/images/mts1.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mts-02', title: 'Black Graphic Tee', price: 319.00, originalPrice: 354.44, description: 'Black Fuel graphic T-shirt made from carded single jersey, with short sleeves and a classic black finish.', image: '/images/mts2.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mts-03', title: 'White and Navy Airtex Inset T-Shirt', price: 260.00, originalPrice: 288.89, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/mts3.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mts-04', title: 'Grey Polo Neck T-shirt', price: 109.00, originalPrice: 121.11, description: 'the Truworths Man Grey Polo Neck T-shirt, featuring long sleeves and crafted from cotton-rich fleece for comfort and style.', image: '/images/mts4.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mts-05', title: 'Borussia Dortmund Special Edition Jersey Men', price: 2320.00, originalPrice: 2577.78, description: 'White Daniel Hechter T-shirt in a cotton-blend knit, featuring short sleeves and a clean white finish.', image: '/images/mts5.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mts-06', title: 'BMW M MOTORSPORT Essentials Tee Men', price: 919.00, originalPrice: 1021.11, description: 'Black Fuel graphic T-shirt made from carded single jersey, with short sleeves and a classic black finish.', image: '/images/mts6.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mts-07', title: 'House of Graphics Record Tee Men', price: 960.00, originalPrice: 1066.67, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/mts7.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mts-08', title: 'Graphic Balloon Art Relaxed Tee Men', price: 649.00, originalPrice: 721.11, description: 'the Truworths Man Grey Polo Neck T-shirt, featuring long sleeves and crafted from cotton-rich fleece for comfort and style.', image: '/images/mts8.jpg', category: 'mens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Men's Pants
  { id: 'mps-01', title: 'PUMA Sport Sweatpants Men', price: 1120.00, originalPrice: 1244.44, description: 'White Daniel Hechter T-shirt in a cotton-blend knit, featuring short sleeves and a clean white finish.', image: '/images/mps1.jpg', category: 'mens-pants', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mps-02', title: 'Essentials No. 1 Logo Slim Sweatpants Men', price: 849.00, originalPrice: 943.33, description: 'Black Fuel graphic T-shirt made from carded single jersey, with short sleeves and a classic black finish.', image: '/images/mps2.jpg', category: 'mens-pants', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mps-03', title: 'PUMA Sport Woven Track Pants Men', price: 260.00, originalPrice: 288.89, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/mps3.jpg', category: 'mens-pants', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mps-04', title: 'PUMATECH Pants Men', price: 1349.00, originalPrice: 1498.89, description: 'the Truworths Man Grey Polo Neck T-shirt, featuring long sleeves and crafted from cotton-rich fleece for comfort and style.', image: '/images/mps4.jpg', category: 'mens-pants', stock: 5, special: true, rating: 0, reviews: 0 },
  
 // Men's Shorts
  { id: 'mss-01', title: 'INDIVIDUAL Padel Training Shorts Men', price: 2320.00, originalPrice: 2577.78, description: 'White Daniel Hechter T-shirt in a cotton-blend knit, featuring short sleeves and a clean white finish.', image: '/images/mss1.jpg', category: 'mens-shorts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mss-02', title: 'Essentials Big No. 1 Logo 10" Shorts Men', price: 619.00, originalPrice: 687.78, description: 'Black Fuel graphic T-shirt made from carded single jersey, with short sleeves and a classic black finish.', image: '/images/mss2.jpg', category: 'mens-shorts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mss-03', title: 'Neymar Jr Playmaker Training Football Shorts Men', price: 850.00, originalPrice: 944.44, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/mss3.jpg', category: 'mens-shorts', stock: 5, special: true, rating: 0, reviews: 0 },
  
 // Men's Jackets
  { id: 'mjk-01', title: 'Essentials No. 1 Logo Track Jacket Men', price: 1149.00, originalPrice: 1276.67, description: 'the Truworths Man Grey Polo Neck T-shirt, featuring long sleeves and crafted from cotton-rich fleece for comfort and style.', image: '/images/mjk1.jpg', category: 'mens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mjk-02', title: 'PUMATECH Relaxed Track Jacket Men', price: 2549.00, originalPrice: 2832.22, description: 'the Truworths Man Grey Polo Neck T-shirt, featuring long sleeves and crafted from cotton-rich fleece for comfort and style.', image: '/images/mjk2.jpg', category: 'mens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mjk-03', title: 'Essentials Elevated Cat Logo Relaxed Sweatshirt Men', price: 2320.00, originalPrice: 2577.78, description: 'White Daniel Hechter T-shirt in a cotton-blend knit, featuring short sleeves and a clean white finish.', image: '/images/mjk3.jpg', category: 'mens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mjk-04', title: 'BMW M MOTORSPORT Lifestyle Relaxed Hoodie Men', price: 619.00, originalPrice: 687.78, description: 'Black Fuel graphic T-shirt made from carded single jersey, with short sleeves and a classic black finish.', image: '/images/mjk4.jpg', category: 'mens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  
   // Men's Caps & Hats
  { id: 'mch-01', title: 'PUMA x ASTON MARTIN ARAMCO F1® TEAM Baseball Cap', price: 850.00, originalPrice: 944.44, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/mch1.jpg', category: 'mens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mch-02', title: 'BMW MMS AOP Bucket Hat', price: 850.00, originalPrice: 944.44, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/mch2.jpg', category: 'mens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Men's Bags
  { id: 'mbs-01', title: 'Training Bottle', price: 249.00, originalPrice: 276.67, description: 'White Daniel Hechter T-shirt in a cotton-blend knit, featuring short sleeves and a clean white finish.', image: '/images/mbs1.jpg', category: 'mens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mbs-02', title: 'PUMA Academy 29L All-Over Print Backpack', price: 619.00, originalPrice: 687.78, description: 'Black Fuel graphic T-shirt made from carded single jersey, with short sleeves and a classic black finish.', image: '/images/mbs2.jpg', category: 'mens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mbs-03', title: 'Academy 2L Waist Bag', price: 850.00, originalPrice: 944.44, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/mbs3.jpg', category: 'mens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Men's Socks
  { id: 'msc-01', title: 'Modalon Golf Polo Men', price: 1300.00, originalPrice: 1444.44, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/msc1.jpg', category: 'mens-socks', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'msc-02', title: 'Mens 3pkTennis Socks', price: 345.00, originalPrice: 383.33, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/msc2.jpg', category: 'mens-socks', stock: 5, special: true, rating: 0, reviews: 0 },

  // Men's Sport
  { id: 'msp-01', title: 'Mens 3 Pk Low Cut Socks', price: 250.00, originalPrice: 277.78, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/msp1.jpg', category: 'mens-sport', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'msp-02', title: 'Manchester City 25/26 Third Jersey Men', price: 1445.00, originalPrice: 1605.56, description: 'White and navy Hemisphere Sport T-shirt made from Airtex fabric, with short sleeves and a breathable, athletic look.', image: '/images/msp2.jpg', category: 'mens-sport', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Fragrances
  { id: 'frg-01', title: 'Lady Million - 30ml', price: 239.00, originalPrice: 265.56, description: 'Lady Million – 30ml: A dazzling, seductive fragrance for women who radiate confidence and luxury with a bold, sensual presence.', image: '/images/frg1.jpg', category: 'fragrances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'frg-02', title: 'Magnetic Impact - 60ml (For Him)', price: 412.00, originalPrice: 457.78, description: 'Magnetic Impact - 60ml (For Him)', image: '/images/frg2.jpg', category: 'fragrances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'frg-03', title: 'Truly Charming - 50ml', price: 430.00, originalPrice: 477.78, description: 'Truly Charming - 50ml', image: '/images/frg3.jpg', category: 'fragrances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'frg-04', title: 'Signature Glow - 50ml (For Her)', price: 322.00, originalPrice: 357.78, description: 'Signature Glow - 50ml (For Her)', image: '/images/frg4.jpg', category: 'fragrances', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'frg-05', title: 'Red Door - 50ml', price: 460.00, originalPrice: 511.11, description: 'Red Door - 50ml', image: '/images/frg5.jpg', category: 'fragrances', stock: 5, special: true, rating: 0, reviews: 0 },

  // Women's Wigs
  { id: 'wwg-01', title: '12'' Afro Kinky Curl Ponytail', price: 1070.00, originalPrice: 1188.89, description: '12'' Afro Kinky Curl Ponytail', image: '/images/wwg1.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-02', title: '10'' Deep Wave Bob 4x4 Wig', price: 2070.00, originalPrice: 2300.00, description: '10'' Deep Wave Bob 4x4 Wig', image: '/images/wwg2.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-03', title: 'Wig Short Curly Human Hair Wigs for Black Women Full Machine Made Wigs Glueless Wig Afro y Curly Wigs', price: 1250.00, originalPrice: 1388.89, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wwg3.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-04', title: 'WERD Long Black Wavy Wigs for Women Black Curly Wig with Middle Part Synthetic 26 Inch', price: 1500.00, originalPrice: 1666.67, description: 'Made from heat-resistant synthetic fiber, this black wig is lightweight, soft, durable, and looks natural with a hand-tied hairline. The curls last longer and the finish is realistic without extra shine.', image: '/images/wwg4.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-05', title: 'Ombre Long Dirty Blonde Wig for Women,26 Inch Wavy Middle Part Wigs', price: 1100.00, originalPrice: 1222.22, description: 'Transform your style instantly with the WERD Long Black Wavy Wig: soft, natural-looking, heat-resistant, and comfortable—perfect for any occasion.', image: '/images/wwg5.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-06', title: 'RENERSHOW Medium Length Blonde Balayage Bob Wig with Bangs for White Women', price: 1399.00, originalPrice: 1554.44, description: 'Step out in style with the RENERSHOW Blonde Balayage Bob Wig—platinum with brown roots, soft and natural-looking, heat-resistant, and comfortable. This chic, layered bob with bangs is easy to wear and perfect for any occasion.', image: '/images/wwg6.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-07', title: 'DULOVE Lace Front Wigs Human Hair Glueless Pre plucked Pre Cut, 24 Inch Human Hair Wig', price: 2199.00, originalPrice: 2443.33, description: 'Experience the DULOVE 24" Glueless Lace Front Wig—100% Brazilian virgin human hair, silky straight, pre-plucked for a natural look. Breathable, comfortable, and easy to style, this wig is perfect for any occasion and stays secure all day without glue.', image: '/images/wwg7.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-08', title: '8 Inch Wigs Human Hair Pre Plucked Pre Cut 4x4 HD Lace Closure Curly Wigs for Black Women Deep Wave Lace Front Glueless', price: 3470.00, originalPrice: 3855.56, description: 'Get easy, natural style with this 8" Wear and Go Glueless Curly Bob Wig—100% human hair, pre-plucked and pre-cut HD lace, comfortable and secure with no glue needed. Full, soft, and beginner-friendly for any occasion.', image: '/images/wwg8.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-09', title: '20" Glueless Brazilian Human Hair Lace Front Wig—soft, straight, and natural', price: 1670.00, originalPrice: 1855.56, description: 'Enhance your style with the Ambeson 20" Glueless Brazilian Human Hair Lace Front Wig—soft, straight, and natural with 13x4 transparent lace. Full, tangle-free, and comfortable, this wig is easy to wear and perfect for any occasion.', image: '/images/wwg9.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-10', title: 'Short Curly Pixie Lace Front Wig—100% Brazilian human hair, natural black, pre-plucked HD lace', price: 600.00, originalPrice: 666.67, description: 'Turn heads with the Profairsor Short Curly Pixie Lace Front Wig—100% Brazilian human hair, natural black, pre-plucked HD lace, and full, bouncy curls. Comfortable, glueless, and easy to wear for any occasion.', image: '/images/wwg10.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wwg-11', title: '12" Straight Highlight Lace Wig—100% human hair, HD lace front, tangle-free', price: 870.00, originalPrice: 966.67, description: 'Shine with the RoseTask 12" Straight Highlight Lace Wig—100% human hair, HD lace front, tangle-free, and easy to style. A secure, natural fit for effortless beauty every day or on special occasions.', image: '/images/wwg11.jpg', category: 'womens-wigs', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Women's T-Shirts
  { id: 'wts-01', title: 'Pink Side Trim Cropped Top', price: 450.00, originalPrice: 500.00, description: 'Inwear Pink Side Trim Cropped Top—a stylish crop top in vibrant pink, crafted from 100% polyester with side trim detail, short sleeves, and a classic crew neck.', image: '/images/wts1.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wts-02', title: 'Striped Oversized Polo Shirt', price: 190.00, originalPrice: 211.11, description: 'a retro-inspired piece with brown and pink stripes, a relaxed fit, and classic polo collar. Crafted from breathable cotton single jersey with a half-button placket and 3/4 sleeves.', image: '/images/wts2.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wts-03', title: 'Blue and White Striped Sweat Shirt', price: 340.00, originalPrice: 377.78, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wts3.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wts-04', title: 'Beige Suiting Cropped Bomber Jacket', price: 600.00, originalPrice: 666.67, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wts4.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wts-05', title: 'PUMA x HYROX Cropped Oversized Lifestyle Tee Women', price: 1050.00, originalPrice: 1166.67, description: 'Inwear Pink Side Trim Cropped Top—a stylish crop top in vibrant pink, crafted from 100% polyester with side trim detail, short sleeves, and a classic crew neck.', image: '/images/wts5.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wts-06', title: 'Graphic Cherry Tee Women', price: 410.00, originalPrice: 455.56, description: 'a retro-inspired piece with brown and pink stripes, a relaxed fit, and classic polo collar. Crafted from breathable cotton single jersey with a half-button placket and 3/4 sleeves.', image: '/images/wts6.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wts-07', title: 'Street Glam Oversized Graphic Tee Women', price: 840.00, originalPrice: 933.33, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wts7.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wts-08', title: 'Run Culture Collective Relaxed Washed Sleeveless Graphic Tee Women', price: 750.00, originalPrice: 833.33, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wts8.jpg', category: 'womens-tshirts', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Women's Pants & Tights
  { id: 'wpt-01', title: 'Essentials No. 1 Logo 7'' Short Leggings Women', price: 500.00, originalPrice: 555.56, description: 'Inwear Pink Side Trim Cropped Top—a stylish crop top in vibrant pink, crafted from 100% polyester with side trim detail, short sleeves, and a classic crew neck.', image: '/images/wpt1.jpg', category: 'womens-pants-tights', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wpt-02', title: 'BMW M MOTORSPORT Relaxed Pants Women', price: 2040.00, originalPrice: 2266.67, description: 'a retro-inspired piece with brown and pink stripes, a relaxed fit, and classic polo collar. Crafted from breathable cotton single jersey with a half-button placket and 3/4 sleeves.', image: '/images/wpt2.jpg', category: 'womens-pants-tights', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wpt-03', title: 'Essentials Sweatpants Women', price: 740.00, originalPrice: 822.22, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wpt3.jpg', category: 'womens-pants-tights', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wpt-04', title: 'Essentials Graphics Bedazzled Slouchy Pants Women', price: 1660.00, originalPrice: 1844.44, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wpt4.jpg', category: 'womens-pants-tights', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wpt-05', title: 'PUMA Class Sweatpants Women', price: 1150.00, originalPrice: 1277.78, description: 'Inwear Pink Side Trim Cropped Top—a stylish crop top in vibrant pink, crafted from 100% polyester with side trim detail, short sleeves, and a classic crew neck.', image: '/images/wpt5.jpg', category: 'womens-pants-tights', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Dresses & Skirts
  { id: 'dsk-01', title: 'T7 Slim Love Of The Cat Full-Zip Dress Women', price: 1540.00, originalPrice: 1711.11, description: 'a retro-inspired piece with brown and pink stripes, a relaxed fit, and classic polo collar. Crafted from breathable cotton single jersey with a half-button placket and 3/4 sleeves.', image: '/images/dsk1.jpg', category: 'dresses-skirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'dsk-02', title: 'T7 Balloon Midi Skirt Women', price: 1899.00, originalPrice: 2110.00, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/dsk2.jpg', category: 'dresses-skirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'dsk-03', title: 'Wardrobe Essentials Cargo Skirt Women', price: 900.00, originalPrice: 1000.00, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/dsk3.jpg', category: 'dresses-skirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'dsk-04', title: 'T7 Midi Pleated Skirt Women', price: 1739.00, originalPrice: 1932.22, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/dsk4.jpg', category: 'dresses-skirts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'dsk-05', title: 'T7 Balloon Skirt Women', price: 1200.00, originalPrice: 1333.33, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/dsk5.jpg', category: 'dresses-skirts', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Women's Shorts
  { id: 'wss-01', title: 'PWRMODE Woven Shorts Women', price: 1620.00, originalPrice: 1800.00, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wss1.jpg', category: 'womens-shorts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wss-02', title: 'FUTURE.PUMA.ARCHIVE Skort Women', price: 1040.00, originalPrice: 1155.56, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wss2.jpg', category: 'womens-shorts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wss-03', title: 'VELOCITY 3" Running Shorts Women', price: 1739.00, originalPrice: 1932.22, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wss3.jpg', category: 'womens-shorts', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wss-04', title: 'Train All Day Essentials 5" High-Waist Shorts Women', price: 850.00, originalPrice: 944.44, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wss4.jpg', category: 'womens-shorts', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Women's Jackets
  { id: 'wjk-01', title: 'T7 Cropped Track Jacket Women', price: 1520.00, originalPrice: 1688.89, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wjk1.jpg', category: 'womens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wjk-02', title: 'Essentials Slim Track Jacket Women', price: 1340.00, originalPrice: 1488.89, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wjk2.jpg', category: 'womens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wjk-03', title: 'FUTURE.PUMA.ARCHIVE T7 Cropped Track Jacket Women', price: 1239.00, originalPrice: 1376.67, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wjk3.jpg', category: 'womens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wjk-04', title: 'Style Jacket Women', price: 2050.00, originalPrice: 2277.78, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wjk4.jpg', category: 'womens-jackets', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Women's Crews & Hoodies
  { id: 'wch-01', title: 'PUMA x HYROX Heavyweight Crew Women', price: 1420.00, originalPrice: 1577.78, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wch1.jpg', category: 'womens-crews-hoodies', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wch-02', title: 'PUMA x HYROX Heavyweight Hoodie Women', price: 1540.00, originalPrice: 1711.11, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wch2.jpg', category: 'womens-crews-hoodies', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wch-03', title: 'Essentials Graphics Animal Hoodie Women', price: 1339.00, originalPrice: 1487.78, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wch3.jpg', category: 'womens-crews-hoodies', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wch-04', title: 'HER Oversized Hoodie Women', price: 1450.00, originalPrice: 1611.11, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wch4.jpg', category: 'womens-crews-hoodies', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wch-05', title: 'Essentials Elevated Logo Sweatshirt Women', price: 1339.00, originalPrice: 1487.78, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wch5.jpg', category: 'womens-crews-hoodies', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wch-06', title: 'Street Glam Bedazzled Hoodie Women', price: 1750.00, originalPrice: 1944.44, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wch6.jpg', category: 'womens-crews-hoodies', stock: 5, special: true, rating: 0, reviews: 0 },
  
 // Women's Underwear & Bras
  { id: 'wub-01', title: 'MOVE PUMA STRONG Bra Women', price: 1450.00, originalPrice: 1611.11, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wub1.jpg', category: 'womens-underwear-bras', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wub-02', title: 'Shapeluxe Mid Sports Bra Women', price: 1339.00, originalPrice: 1487.78, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wub2.jpg', category: 'womens-underwear-bras', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wub-03', title: 'Street Glam Bedazzled Hoodie Women', price: 1750.00, originalPrice: 1944.44, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wub3.jpg', category: 'womens-underwear-bras', stock: 5, special: true, rating: 0, reviews: 0 },
  
// Women's Caps & Hats
  { id: 'wc1-01', title: 'BMW M Motorsport Heritage Dad Cap', price: 550.00, originalPrice: 611.11, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wc11.jpg', category: 'womens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wc1-02', title: 'Essentials No.1 Logo Bucket Hat', price: 409.00, originalPrice: 454.44, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wc12.jpg', category: 'womens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wc1-03', title: 'Prime Graphic Dad Cap', price: 509.00, originalPrice: 565.56, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wc13.jpg', category: 'womens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wc1-04', title: 'Amara Pink Winter Wrap', price: 400.00, originalPrice: 444.44, description: 'Amara Pink Winter Wrap', image: '/images/wc14.jpg', category: 'womens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wc1-05', title: 'Sierra Straw hat With Bow - Black', price: 319.00, originalPrice: 354.44, description: 'Sierra Straw hat With Bow - Black', image: '/images/wc15.jpg', category: 'womens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wc1-06', title: 'Lucia Wide Brim Hat', price: 319.00, originalPrice: 354.44, description: 'Lucia Wide Brim Hat', image: '/images/wc16.jpg', category: 'womens-caps-hats', stock: 5, special: true, rating: 0, reviews: 0 },
  
// Women's Bags
  { id: 'wbs-01', title: 'PUMA Deck 2.2L Waist Bag', price: 409.00, originalPrice: 454.44, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wbs1.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wbs-02', title: '2 colours Fundamental 20L Backpack', price: 700.00, originalPrice: 777.78, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wbs2.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wbs-03', title: 'PUMA Phase Backpack II', price: 629.00, originalPrice: 698.89, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wbs3.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wbs-04', title: 'PUMA Sense Mellow Medium Prism Bag', price: 1450.00, originalPrice: 1611.11, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wbs4.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wbs-05', title: 'Challenger 58L Medium Sports Bag', price: 950.00, originalPrice: 1055.56, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wbs5.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wbs-06', title: 'Fundamental 34L Small Sports Bag', price: 750.00, originalPrice: 833.33, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wbs6.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wbs-07', title: 'Tracey Satchel - Cream & Tan', price: 770.00, originalPrice: 855.56, description: 'Tracey Satchel - Cream & Tan', image: '/images/wbs7.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wbs-08', title: 'Tracey Crossbody - Cream & Tan', price: 630.00, originalPrice: 700.00, description: 'Tracey Crossbody - Cream & Tan', image: '/images/wbs8.jpg', category: 'womens-bags', stock: 5, special: true, rating: 0, reviews: 0 },
  
// Women's Socks
  { id: 'wsc-01', title: 'Single Mid calf Cow sock', price: 209.00, originalPrice: 232.22, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/wsc1.jpg', category: 'womens-socks', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'wsc-02', title: 'Ladies 3pk Low sock', price: 250.00, originalPrice: 277.78, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/wsc2.jpg', category: 'womens-socks', stock: 5, special: true, rating: 0, reviews: 0 },
  
// Sport Gear For Women
  { id: 'sgw-01', title: 'Sport Golf Visor', price: 400.00, originalPrice: 444.44, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/sgw1.jpg', category: 'sport-gear-women', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'sgw-02', title: 'Houndstooth Quarter-Zip Golf Top Women', price: 1550.00, originalPrice: 1722.22, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/sgw2.jpg', category: 'sport-gear-women', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'sgw-03', title: 'Birdseye Sleeveless Golf Polo Women', price: 999.00, originalPrice: 1110.00, description: 'This classic, nautical-inspired pullover features blue and white horizontal stripes, signature embroidery, a comfortable crew neck, and long sleeves.', image: '/images/sgw3.jpg', category: 'sport-gear-women', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'sgw-04', title: 'Lettie Golf Skirt Women', price: 1000.00, originalPrice: 1111.11, description: 'a modern classic in a versatile beige polyblend suiting fabric, perfect for adding a casual edge to any look.', image: '/images/sgw4.jpg', category: 'sport-gear-women', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Makeup
  { id: 'mkp-01', title: '6 Matte Lipstick with 6 Lipliners Durable Lip Gloss(12PCS)', price: 528.00, originalPrice: 586.67, description: '12-piece Lip Gloss Kit, featuring 6 matte liquid lipsticks with matching lip liners and a moisturizing lip primer. Enjoy long-lasting, waterproof, and non-stick cup color in a range of high-pigment nude shades. The cruelty-free, semi-matte formula is moisturizing, comfortable, and stays flawless for up to 12 hours. Presented in a stylish gift box, this set is perfect for any occasion.', image: '/images/mkp1.jpg', category: 'makeup', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mkp-02', title: 'Black Opal True Colour SPF15 Skin Perfecting Stick Foundation 14 g, Warm Almond', price: 445.00, originalPrice: 494.44, description: 'Achieve a flawless finish with Black Opal True Colour SPF15 Skin Perfecting Stick Foundation in Warm Almond. This long-wear, full-coverage foundation stick features shade ID technology for a perfect match, is paraben-free, and is infused with vitamins C and E to nourish and brighten. Suitable for combination, dry, and normal skin types, it delivers buildable coverage, hydration, and SPF 15 protection for radiant, protected skin all day.', image: '/images/mkp2.jpg', category: 'makeup', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mkp-03', title: 'Eyeshadow Palette 10 g, 10 Pretty In Nude', price: 160.00, originalPrice: 177.78, description: 'This compact 10g palette features super-soft, easy-to-apply powders that deliver rich, vibrant color payoff. Perfect for defining eyes with both subtle and bold looks, it’s ideal for travel and on-the-go touch-ups.', image: '/images/mkp3.jpg', category: 'makeup', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mkp-04', title: 'Maybelline New York Lash Sensational Sky High Mascara, Volumising & Lengthening Mascara', price: 275.00, originalPrice: 305.56, description: '7.2 ml, Washable Flake-Free Formula Infused with Bamboo Extract & Fibres, Shade: 01, Black | With Bamboo Extract, Eyelash Lengthening, Flake-Free Formula, Washable Mascara, Full Volume', image: '/images/mkp4.jpg', category: 'makeup', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'mkp-05', title: 'Makeup Brush Set', price: 229.00, originalPrice: 254.44, description: '15-piece Premium Professional Makeup Brush Set. Featuring soft, silky nylon bristles and 2 triangle puffs, this versatile set covers all your contouring, blending, coloring, and highlighting needs. The brushes are fine, dense, and suitable for sensitive skin, ensuring flawless application and long-lasting use. Perfect for makeup beginners and enthusiasts, and makes an ideal gift for any occasion.', image: '/images/mkp5.jpg', category: 'makeup', stock: 5, special: true, rating: 0, reviews: 0 },
  
// Leggings
  { id: 'lgs-01', title: '2-Pack Brown & Black Cabled Leggings', price: 450.00, originalPrice: 500.00, description: 'comfort and style with the Ginger Mary 2-Pack Brown & Black Cabled Leggings. These seamless, mid-waist leggings come in a versatile pack of two for everyday wear.', image: '/images/lgs1.jpg', category: 'leggings', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'lgs-02', title: 'Grey & Black High-Rise Leggings 2-Pack', price: 450.00, originalPrice: 500.00, description: 'the OUTBACK RED Sport Grey & Black High-Rise Leggings 2-Pack. These seamless leggings feature a soft feel, wide waistband, and streamlined silhouette in versatile grey and black.', image: '/images/lgs2.jpg', category: 'leggings', stock: 5, special: true, rating: 0, reviews: 0 },
  { id: 'lgs-03', title: 'Navy Printed Pyjama Set', price: 619.00, originalPrice: 681.00, description: 'classic button-down set features an all-over "Lazy Days" print, soft poly knit fabric, and pink piping for a comfortable, stylish lounge look.', image: '/images/lgs3.jpg', category: 'leggings', stock: 5, special: true, rating: 0, reviews: 0 },
  
  // Jewelry
  { id: 'jw-1', title: '10Pcs 14K Gold Plated French Earrings Hooks 10x16mm', price: 739.00, description: 'Enhance your jewelry creations with this 10-piece set of 14K gold-plated French earring hooks. Each 10x16mm hypoallergenic sterling silver hook features a secure loop and replaceable leverback design, ideal for dangle and hoop earrings. Perfect for DIY jewelry making and sensitive ears.', image: '/images/hoop-earrings.jpg', category: 'jewelry', stock: 18, trending: true, rating: 4.6, reviews: 24 },
  { id: 'jw-2', title: 'Necklaces for Women, 14K-Gold-Plated Layering Hexagon Letter ', price: 700.00, description: 'Necklace set. Featuring two 14K gold-plated brass paperclip chains (18"+2" and 14"+2" extensions), this layered design includes a hexagon charm engraved with your initial and a heart. Perfect for women and teen girls, it arrives in an elegant gift box—ideal for gifting or everyday wear. Nickel-free, no gemstone, and suitable for ages 6+.', image: '/images/layered-necklace.jpg', category: 'jewelry', stock: 14, rating: 4.4, reviews: 16 },
  { id: 'jw-3', title: 'Italian Charms Bracelet Set 9 modular 9mm charms', price: 930.00, description: 'a classic starter bracelet, 9 modular 9mm charms, and a handy tool for easy assembly. Made from durable stainless steel in silver and gold tones, the charms feature retractable snaps for effortless customization. Compatible with major Italian charm brands and perfect for gifting or DIY moments with loved ones.', image: '/images/charm-bracelet.jpg', category: 'jewelry', stock: 22, new: true, rating: 4.3, reviews: 11 },
  { id: 'jw-4', title: '6 Pairs 14K Gold Plated Stud Earrings Set For Women', price: 482.00, description: '6 Pairs 14K Gold Plated Stud Earrings Set: Includes hypoallergenic, nickel- and lead-free stud and hoop earrings in classic, dainty styles—perfect for stacking and everyday wear. Durable, shiny, and safe for sensitive ears. Comes in gift-ready packaging, ideal for multiple piercings or gifting.', image: '/images/stud-set.jpg', category: 'jewelry', stock: 25, rating: 4.5, reviews: 19 },
 
  // Hair Dye
  { id: 'hd-1', title: 'Garnier Nutrisse Creme Permanent Hair Dye, No. 1 Black', price: 199.00, description: 'Garnier Nutrisse Creme Permanent Hair Dye, No. 1 Black: Ultra-nourishing permanent dye for all hair types. Delivers rich, natural-looking color with a blend of four botanical oils, hydrating hair and helping prevent breakage for salon-quality results at home.', image: '/images/black-dye.jpg', category: 'hair-dye', stock: 20, rating: 4.2, reviews: 15 },
  { id: 'hd-2', title: 'Revlon ColorStay Longwear Cream Hair Color, Intense Red', price: 194.00, description: 'Revlon ColorStay Longwear Cream Hair Color, Intense Red: High-performance, creamy, non-drip formula for all hair types. Provides rich, vibrant, long-lasting color with full grey coverage. ColorStay technology and the Colour Booster Mask keep color vibrant for up to 8 weeks. Vegan, mineral oil- and silicone-free.', image: '/images/burgundy-dye.jpg', category: 'hair-dye', stock: 15, trending: true, rating: 4.4, reviews: 22 },
  { id: 'hd-3', title: 'Honey Blonde Creme of Nature Moisture Rich Hair Color Kit, C41', price: 409.00, description: 'Creme of Nature Moisture Rich Hair Color Kit, C41 Honey Blonde: Long-lasting, moisture-rich color for all hair types. Infused with silk proteins for soft, smooth, shiny hair that looks healthier after coloring. Deeply nourishing conditioner included.', image: '/images/blonde-dye.jpg', category: 'hair-dye', stock: 12, rating: 4.3, reviews: 13 },

  // Hair Styling Tools
  { id: 'hs-1', title: 'Professional Hair Straightener', price: 229.00, originalPrice: 249.00, description: 'Professional Hair Straightener: Features keratin-infused ceramic plates and heats up to 750°F for fast, salon-quality styling. Anti-tangle, anti-snag design with 3D styling for straightening, curling, or flipping. Lightweight, ergonomic, and finished in matte black.', image: '/images/straightener.jpg', category: 'hair-styling', stock: 8, special: true, rating: 4.7, reviews: 31 },
  { id: 'hs-2', title: 'Professional Curling Iron (9mm/19mm/25mm)', price: 330.00, description: 'Professional Curling Iron (9mm/19mm/25mm): Ceramic tourmaline curler delivers long-lasting, bouncy curls with minimal heat damage and less frizz. Heats up in 30 seconds, offers 5 adjustable temperatures (250°F–450°F), and suits all hair types. Lightweight, ergonomic, and user-friendly for salon-quality curls at home.', image: '/images/curling-wand.jpg', category: 'hair-styling', stock: 10, rating: 4.5, reviews: 18 },
  { id: 'hs-3', title: 'Philips 3000 Series 2100W Hair Dryer', price: 580.00, description: 'Philips 3000 Series 2100W Hair Dryer: Fast-drying hair dryer with ionic technology to reduce frizz and minimize heat damage. Features a cool air setting to lock in style and an elegant, modern design.', image: '/images/hair-dryer.jpg', category: 'hair-styling', stock: 12, trending: true, rating: 4.6, reviews: 25 },
  { id: 'hs-4', title: 'ALANES Hair Brush Set (Eight-Pink)', price: 239.00, description: 'ALANES Hair Brush Set (Eight-Pink): 8-in-1 set includes detangler brush, rat tail comb, edge brush, bristle brush, spray bottle, braiding tool, hair tie, and loop styling tools. Ergonomic, non-slip handles and soft bristles gently massage the scalp, suitable for all hair types—wet or dry. Ideal for painless, smooth styling and daily hair care.', image: '/images/brush-set-hair.jpg', category: 'hair-styling', stock: 18, rating: 4.2, reviews: 14 },

  // Hair & Scalp Treatments
  { id: 'ht-1', title: 'Afri Pure Hair & Scalp Oil Elixir (Rosemary & Mint, 100ml)', price: 90.00, description: 'Hair Growth Oil, Strengthens and nourishes all hair types with a refreshing scent. Alcohol-free, cruelty-free, 100% vegan, and packaged in a recyclable bottle.', image: '/images/hair-oil.jpg', category: 'hair-treatment', stock: 16, trending: true, rating: 4.5, reviews: 28 },
  { id: 'ht-2', title: 'Palmer Cocoa Butter Length Retention Deep Conditioner (340g)', price: 209.00, description: 'Silicone-free, vegan, and cruelty-free deep conditioner for all hair types, especially curly, damaged, or dry hair. Nourishes, strengthens, moisturizes, and repairs split ends while improving shine, softness, and elasticity.', image: '/images/conditioner.jpg', category: 'hair-treatment', stock: 20, rating: 4.4, reviews: 19 },
  { id: 'ht-3', title: 'Organics Green Tea Anti Dandruff 2in1 Shampoo & Conditioner (1L)', price: 140.00, description: ' Petrochemical-free, gentle care for all hair types. Contains green tea extract to hydrate, nourish, and revive hair. Cleanses and moisturizes in one step for over 150 uses, leaving hair shiny and dandruff-free.', image: '/images/dandruff-shampoo.jpg', category: 'hair-treatment', stock: 14, rating: 4.3, reviews: 16 },

  // Body-care for Men
  { id: 'bm-1', title: 'NIVEA MEN Active Clean 3-in-1 Shower Gel (500ml)', price: 149.00, description: 'Deep-cleansing gel with active charcoal and purifying beads for body, face, and hair. Provides intensive hydration, exfoliates, and leaves skin feeling refreshed and clean. Suitable for all skin types.', image: '/images/body-wash-men.jpg', category: 'bodycare-men', stock: 25, trending: true, rating: 4.4, reviews: 22 },
  { id: 'bm-2', title: 'Beard Grooming Kit for Men', price: 109.00, description: 'Includes beard shampoo, beard growth oil, and beard balm with natural ingredients to promote thicker, fuller beards. Keeps beards clean, soft, and well-shaped. Suitable for all beard types and ideal as a gift for birthdays, Christmas, or Father's Day.', image: '/images/beard-kit.jpg', category: 'bodycare-men', stock: 12, rating: 4.6, reviews: 15 },
  { id: 'bm-3', title: 'Shield Men Fresh Xtra Cool Anti-Perspirant Roll-On (50ml)', price: 20.00, description: 'Aluminum-free deodorant offers 72-hour sweat protection, prevents white marks and yellow stains, and features a motion-activated formula for all-day freshness and confidence. Biodegradable and fresh-scented.', image: '/images/deodorant.jpg', category: 'bodycare-men', stock: 30, rating: 4.2, reviews: 18 },
  { id: 'bm-4', title: 'Vaseline Blue Seal Original Petroleum Jelly 450ml', price: 90.00, description: 'Vaseline Blue Seal Original Petroleum Jelly 450ml soothes dry skin, protects minor cuts, and locks in moisture. 100% pure, hypoallergenic, and safe for daily use.', image: '/images/face-cream-men.jpg', category: 'bodycare-men', stock: 18, rating: 4.5, reviews: 12 },

  // Body-care for Women
  { id: 'bm-3', title: 'NIVEA Rose and Almond Oil Caring Shower Gel 500 ml', price: 120.00, description: 'NIVEA Rose & Almond Oil Caring Shower Gel 500ml pampers your skin with the delicate scent of rose and nourishing almond oil. Its creamy, microplastic-free formula gently cleanses and hydrates, leaving skin soft, smooth, and refreshed. Suitable for all skin types and dermatologically approved, this shower gel supports your skin’s natural pH balance for a radiant glow.', image: '/images/deodorant.jpg', category: 'bodycare-men', stock: 30, rating: 4.2, reviews: 18 },
  { id: 'bm-4', title: 'NIVEA LUMINOUS630 Bubble Face Cleansing Foam 100ml', price: 135.00, description: 'NIVEA LUMINOUS630 Bubble Face Cleansing Foam 100ml deeply cleanses and removes makeup, revealing brighter, more youthful-looking skin. Featuring a 6 Acid Complex and Pearl Rucinol Combo, it visibly reduces dullness and balances oil for a radiant glow. Non-comedogenic, alcohol-free, and suitable for all skin types.', image: '/images/face-cream-men.jpg', category: 'bodycare-men', stock: 18, rating: 4.5, reviews: 12 },
  { id: 'bm-3', title: 'NIVEA Pearl & Beauty Anti-Perspirant Roll-On Deodorant (50ml)', price: 23.00, description: 'Alcohol-free gel formula offers 48-hour sweat and odor protection. Enriched with natural pearl extract and avocado oil for soft, smooth underarms with a fresh floral scent. Travel-friendly and gentle on skin.', image: '/images/deodorant.jpg', category: 'bodycare-men', stock: 30, rating: 4.2, reviews: 18 },
  { id: 'bm-4', title: 'Rexona Female Oxygen Antiperspirant Roll-On Deodorant (50ml)', price: 20.00, description: 'Provides up to 72-hour sweat and odor protection with a clean, fresh scent. Smooth roll-on application, travel-size, and designed for high-performance, all-day use.', image: '/images/face-cream-men.jpg', category: 'bodycare-men', stock: 18, rating: 4.5, reviews: 12 },
  
  // Textbooks
  { id: 'tb-1', title: 'Business Management: An African Perspective', price: 649.00, description: 'This introductory Business Management textbook is ideal for undergraduate students in South Africa, Africa, and globally. Covering essential topics such as general management, finance, operations, supply chain, HR, marketing, entrepreneurship, business ethics, and 4IR trends, it offers a comprehensive, practical foundation for future business leaders. Written by expert academics and industry professionals, the book blends theory with real-world applications to prepare students for success in the business world.', image: '/images/management-book.jpg', category: 'textbooks', stock: 8, trending: true, rating: 4.3, reviews: 9 },
  { id: 'tb-2', title: 'Financial Accounting: An introduction 6e', price: 799.00, description: 'An Introduction 6th edition is designed for first-year financial accounting students at universities and universities of technology. It provides a solid foundation for both chartered and general accounting streams. Using a narrative approach, the book explains accounting concepts through real-world problems faced by a young entrepreneur, making learning relevant and engaging. Solutions are provided to guide students through each concept.', image: '/images/economics-book.jpg', category: 'textbooks', stock: 6, rating: 4.4, reviews: 7 },
  { id: 'tb-3', title: 'The Psychology of Money: Timeless lessons on wealth, greed, and happiness', price: 475.00, description: 'The Psychology of Money by Morgan Housel reveals how our behavior shapes financial success more than knowledge alone. Through 19 engaging stories, this bestselling book explores the emotional and psychological factors behind money decisions, offering timeless lessons on wealth, greed, and happiness for readers seeking smarter financial choices.', image: '/images/calculus-book.jpg', category: 'textbooks', stock: 5, rating: 4.5, reviews: 6 },
  { id: 'tb-4', title: 'The Magic of Thinking Big: (Vermilion Life Essentials)', price: 389.00, description: 'The Magic of Thinking Big by Dr. David Schwartz is a classic self-help guide that empowers you to achieve more by changing the way you think. With practical, step-by-step strategies, this bestselling book helps you overcome doubt, develop positive thinking, and build a personal plan for success in all areas of life.', image: '/images/psychology-book.jpg', category: 'textbooks', stock: 7, rating: 4.2, reviews: 8 },

  // Toys & Games
  { id: 'tg-1', title: 'Drift Car 30KM/H 1:16 scale 4WD RC ', price: 1179.00, description: 'This 1:16 scale RC Drift Car features 4WD, dual motors, and speeds up to 30KM/H for precise drifting on any terrain. With cool LED lights, two rechargeable batteries for up to 2 hours of play, and a 2.4GHz remote with a 165ft range, perfect for night racing and display. Ideal gift for kids and adults alike.', image: '/images/uno.jpg', category: 'toys-games', stock: 20, trending: true, rating: 4.8, reviews: 42 },
  { id: 'tg-2', title: ' Travel Chess Set includes Chess, Backgammon, and Checkers, all in one', price: 220.00, description: 'This compact wooden Marco Travel Set includes Chess, Backgammon, and Checkers, all in one. Designed for two players, it features a hinged case for easy transport and comes in a stylish brown and natural finish. Perfect for adults on the go.', image: '/images/chess.jpg', category: 'toys-games', stock: 10, rating: 4.6, reviews: 15 },
  { id: 'tg-3', title: 'Monopoly The Mega Edition', price: 2100.00, description: 'Monopoly The Mega Edition by Winning Moves is a bigger, faster version of the classic game. With extra properties, Train Depots, Skyscrapers, and the Speed Die, games last about 90 minutes. Supports 2–8 players, ages 8+, and features all your favorite Monopoly tokens for exciting family fun.', image: '/images/jenga.jpg', category: 'toys-games', stock: 14, rating: 4.5, reviews: 21 },
  { id: 'tg-4', title: 'Monopoly Stitch Edition classic Monopoly gameplay', price: 649.00, description: 'Monopoly Stitch Edition brings classic Monopoly gameplay with a fun Disney Lilo & Stitch twist! Play as Stitch with 4 unique tokens, claim activities and beach rentals instead of properties, and build beach huts and lighthouses. Perfect for family game night and Disney fans of all ages.', stress reliever', image: '/images/fidget-cube.jpg', category: 'toys-games', stock: 30, rating: 4.3, reviews: 18 },

  // Earphones & Headphones
  { id: 'ep-1', title: 'HUAWEI FreeBuds SE 2 Wireless Earbuds', price: 400.00, description: 'HUAWEI FreeBuds SE 2 Wireless Earbuds offer up to 40 hours of battery life, fast charging, and crisp Bluetooth audio in a compact, comfortable design. With IP dust and splash resistance, perfect for workouts or travel. Enjoy hassle-free listening on the go, with just 10 minutes of charging for hours of playtime.', image: '/images/wired-earphones.jpg', category: 'earphones', stock: 25, rating: 4.2, reviews: 28 },
  { id: 'ep-2', title: 'Volkano Sleek Series True Wireless Bluetooth Earphones', price: 349.00, originalPrice: 366.00, description: 'deliver powerful sound with 13mm drivers and up to 6 hours of battery life. Enjoy stable Bluetooth 5.3 connectivity, quick USB-C charging, and an ergonomic, lightweight design. With IPX4 water resistance, ideal for workouts and everyday use. Includes charging cable.', image: '/images/wireless-earbuds.jpg', category: 'earphones', stock: 15, special: true, rating: 4.6, reviews: 35 },
  { id: 'ep-3', title: 'Amplify Stellar Series Bluetooth Headphones', price: 400.00, description: 'deliver up to 55 hours of wireless playtime, with 40mm drivers for clear, balanced sound. Enjoy Bluetooth or AUX connectivity, USB-C fast charging, built-in mic, FM radio, and TF card support—all in a comfortable over-ear design. Accessories included.', image: '/images/headphones.jpg', category: 'earphones', stock: 10, trending: true, rating: 4.7, reviews: 24 },
  { id: 'ep-4', title: 'Volkano Pebble Bluetooth Headphones', price: 400.00, description: 'Volkano Pebble Bluetooth Headphones offer up to 75 hours of playtime, crisp audio with 40mm drivers, and a comfortable, durable design. Enjoy stable Bluetooth connectivity up to 10m, USB-C charging, and compatibility with laptops and smartphones—perfect for all-day listening.', image: '/images/gaming-headset.jpg', category: 'earphones', stock: 12, rating: 4.4, reviews: 19 },
  { id: 'ep-4', title: 'VolkanoX VXH300 Bluetooth Headphones', price: 1350.00, description: 'VolkanoX VXH300 Bluetooth Headphones feature Hybrid Active Noise Cancelling, Upto 55 hours play time, Bluetooth 5.0, and Duo mode for wired or wireless listening. With a sleek, portable design, built-in mic, and fast 1-hour charging, these headphones deliver immersive sound and all-day battery life for work, travel, or relaxation.', image: '/images/gaming-headset.jpg', category: 'earphones', stock: 12, rating: 4.4, reviews: 19 },

// Perfume
  { id: 'pf-1', title: 'Playboy Limitless Aerosol Deodorant 150ml ', price: 66.00, description: 'Playboy Limitless Aerosol Deodorant 150ml offers a bold, fresh masculine scent inspired by exotic notes. Aluminum-free and toxic-free, it provides all-day protection—perfect for daily use to keep you smelling your best.', image: '/images/aqua-perfume.jpg', category: 'perfume', stock: 10, trending: true, rating: 4.5, reviews: 16 },
  { id: 'pf-2', title: 'Playgirl Spritzer Sweet Vanilla 150ml', price: 83.00, description: 'Playgirl Spritzer Sweet Vanilla 150ml is a light, refreshing body mist with a warm vanilla scent. Perfect for daily wear, post-shower freshness, or on-the-go fragrance boosts. Enjoy long-lasting value in a convenient spritzer bottle.', image: '/images/floral-perfume.jpg', category: 'perfume', stock: 8, rating: 4.6, reviews: 13 },

// Phone & Laptop Stickers
  { id: 'st-1', title: '200 PCS Funny Holographic Stickers for Laptop', price: 600.00, description: 'This LakoArt pack includes 200 unique holographic waterproof vinyl stickers for adults, featuring funny, sarcastic, and meme designs. Perfect for laptops, water bottles, phones, journals, scrapbooks, and more. Easy to peel, stick, and remove without residue—add personality and humor to any surface', image: '/images/sticker-pack.jpg', category: 'stickers', stock: 30, trending: true, rating: 4.5, reviews: 32 },
  { id: 'st-2', title: '480 waterproof vinyl stickers Perfect for scrapbooking, journaling, laptops', price: 519.00, description: '480 waterproof vinyl stickers in four color themes: Pink, Brown, Red, and Black & White. Perfect for scrapbooking, journaling, laptops, water bottles, and DIY crafts. Durable, vibrant, and easy to remove, these stickers add a stylish touch to any project and make a great gift for all ages.', image: '/images/aesthetic-stickers.jpg', category: 'stickers', stock: 25, rating: 4.3, reviews: 19 },
  { id: 'st-3', title: 'Laptop Decal Sticker Skin Cover fits most 12"–15.6', price: 815.00, description: 'ToLuLu Laptop Decal Sticker Skin Cover fits most 12"–15.6" laptops, offering durable, high-resolution protection against scratches and dust. Made from waterproof, reusable vinyl, easy to apply, remove, and trim for a custom fit. Includes two matching wrist pads—perfect for a stylish, practical gift.', image: '/images/laptop-skin.jpg', category: 'stickers', stock: 18, rating: 4.4, reviews: 14 },
  { id: 'st-3', title: 'Purple Marble Laptop Decal Sticker fits 12"–15.6" laptops', price: 790.00, description: 'This ToLulu Purple Marble Laptop Decal Sticker fits 12"–15.6" laptops, offering high-resolution, waterproof, and reusable protection. Easy to apply, remove, and trim for a perfect fit. Includes two matching wrist pads—ideal for stylish scratch and dust protection or as a practical gift.', image: '/images/laptop-skin.jpg', category: 'stickers', stock: 18, rating: 4.4, reviews: 14 },
  { id: 'st-3', title: '220 large waterproof vinyl meme stickers for personalizing laptops', price: 199.00, description: 'perfect for personalizing laptops, phones, skateboards, luggage, and more. Features trendy and funny designs, easy peel-and-stick application, and durable material for long-lasting use.', image: '/images/laptop-skin.jpg', category: 'stickers', stock: 18, rating: 4.4, reviews: 14 },
  { id: 'st-3', title: '200 unique, cute waterproof vinyl stickers for Laptops', price: 600.00, description: 'This Eoaod pack includes 200 unique, cute waterproof vinyl stickers for kids and teens—no duplicates. Perfect for water bottles, laptops, skateboards, and more. Durable, reusable, and easy to remove without residue, these vibrant stickers are ideal for decorating or gifting.', image: '/images/laptop-skin.jpg', category: 'stickers', stock: 18, rating: 4.4, reviews: 14 },

  // Manicure & Pedicure
  { id: 'mp-1', title: '7-piece Professional Manicure Set', price: 292.00, description: 'This 7-piece Professional Manicure Set by Petight includes stainless steel nail clippers, eyebrow tools, and more, all in a sleek leather case. Portable and rust-resistant, perfect for grooming at home or on the go—a stylish gift for men.', image: '/images/nail-clipper.jpg', category: 'manicure', stock: 20, rating: 4.3, reviews: 16 },
  { id: 'mp-2', title: 'The Sioux Cat Eye Gel Nail Polish Set', price: 269.00, description: 'The Sioux Cat Eye Gel Nail Polish Set (Aurora Lights) features 3 magnetic cat eye gel colors with a shimmering, velvet-like finish. Includes a magnet for easy 3D effects, a low-odor vegan formula, and salon-quality, chip-resistant wear for up to 28 days. Perfect for gifting or DIY manicures.', image: '/images/nail-polish.jpg', category: 'manicure', stock: 15, trending: true, rating: 4.5, reviews: 22 },
  { id: 'mp-3', title: 'Electric Nail Drill 6 in 1', price: 429., description: 'The Atopskins Electric Nail Drill 6 in 1 is a cordless, professional manicure set with adjustable speeds up to 45,000 RPM. It includes 6 drill bits, sanding bands, a double-sided emery board, and a rechargeable 2000mAh battery for up to 10 hours of use. Perfect for acrylic, gel, or natural nails—compact, portable, and easy to use for beginners and pros alike.', image: '/images/nail-drill.jpg', category: 'manicure', stock: 8, rating: 4.4, reviews: 12 },

  //Extra hotness Hoodies & Sweatshirts
  { id: 'hs-2', title: 'Grey Graphic Sweatshirt', price: 499.00, description: 'Grey Graphic Sweatshirt by Fuel features a primary colour of grey, long sleeves, and is crafted from soft polyfleece fabric. This stylish sweatshirt combines comfort and warmth, making it a versatile addition to any wardrobe.', image: '/images/grey-sweatshirt.jpg', category: 'hoodies', stock: 12, rating: 4.4, reviews: 17 },
   { id: 'hs-4', title: 'The Columbia Men DriVenture™ Half Zip Shirt', price: 859.00, description: 'engineered for high-performance outdoor activity in challenging conditions, featuring a blend of 55% polypropylene and 45% polyester. Its Omni-Wick Evap technology rapidly wicks moisture to the fabric’s surface for quick evaporation, ensuring comfort during heat and intense activity. Omni-Shade UPF 50 offers advanced protection against harmful UVA/UVB rays, while ergonomic seams provide a better fit and enhanced movement. The shirt is designed with thumbholes on the cuffs to keep sleeves in place and add hand coverage, and a chin guard to prevent chafing. Care instructions include machine wash cold gentle, no bleach, tumble dry low, remove promptly, iron low, do not use fabric softener, do not iron decal if present, and do not dryclean. The regular fit and advanced features make this Columbia Titanium style ideal for active outdoor enthusiasts.', image: '/images/cropped-sweat.jpg', category: 'hoodies', stock: 14, rating: 4.3, reviews: 11 },
  { id: 'hs-2', title: 'EFAN Women Oversized Sweatshirt Hoodie (Meduim size only)', price: 400.00, description: '(Meduim size Only available), EFAN Women Oversized Sweatshirt Hoodie blends 50% cotton and 50% polyester for lightweight warmth and comfort. Featuring an oversized fit, fleece lining, and drop shoulder design, this pullover is stylish and cozy for fall and winter. Easy to pair with jeans or leggings, it suits casual outings, daily wear, and various activities. Machine washable for effortless care.', image: '/images/grey-sweatshirt.jpg', category: 'hoodies', stock: 12, rating: 4.4, reviews: 17 },
  { id: 'hs-2', title: 'Yescool Wearable Blanket Hoodie', price: 380.00, description: 'The yescool Wearable Blanket Hoodie is an oversized flannel and synthetic sherpa sweatshirt designed for maximum warmth and comfort. Featuring a hood, pocket, and sleeves, this one-size-fits-all hoodie is perfect for gifting on birthdays, Christmas, and other special occasions. Its reinforced seams and thoughtful length ensure durability and ease of movement, while the plush lining keeps you cozy during cold weather. Available in multiple colors, it’s an ideal choice for anyone seeking stylish, practical comfort at home or outdoors.', image: '/images/grey-sweatshirt.jpg', category: 'hoodies', stock: 12, rating: 4.4, reviews: 17 },
  { id: 'hs-3', title: 'White Oversized Racoon Hoodie', price: 619.00, description: 'the White Oversized Racoon Hoodie by Inwear, highlighting its colour, style, soft brushed stretch fleece fabric, and comfortable long sleeves for a modern, relaxed look.', image: '/images/oversized-hoodie.jpg', category: 'hoodies', stock: 10, new: true, rating: 4.5, reviews: 14 },
  { id: 'hs-4', title: 'Black Faux Fur Cropped Bolero Jacket', price: 859.00, description: 'the Black Faux Fur Cropped Bolero Jacket by Truworths, highlighting its plush faux fur, elegant details, and statement-making style for evening occasions.', image: '/images/cropped-sweat.jpg', category: 'hoodies', stock: 14, rating: 4.3, reviews: 11 },
   { id: 'hs-4', title: 'Missy Missi Ladies Cropped Shirt with Long Sleeves (Size XL)', price: 379.00, description: 'The Missy Missi Ladies Cropped Shirt with Long Sleeves in XL is a stylish, casual piece crafted from lightweight, high-quality polyester for comfort and breathability. Featuring a button front and a trendy cropped length, this slim-fit shirt accentuates the waistline and offers a modern, chic look. Ideal for upgrading your wardrobe with a versatile and reusable fashion staple.', image: '/images/cropped-sweat.jpg', category: 'hoodies', stock: 14, rating: 4.3, reviews: 11 },


  //Extra hotness Sunglasses Men and Women
  { id: 'sg-1', title: 'Classic Metal Aviator Sunglasses for Men & Women', price: 852.00, description: 'Classic Metal Aviator Sunglasses combine a timeless aviator design with a lightweight, durable metal frame, suitable for men and women. The polarized, UV-protective lenses reduce glare and safeguard your eyes, while adjustable nose pads and smooth temple tips ensure lasting comfort. Perfect for everyday wear, driving, or outdoor activities, these sunglasses offer versatile style and dependable eye protection.', image: '/images/aviators.jpg', category: 'sunglasses', stock: 18, trending: true, rating: 4.5, reviews: 24 },
   { id: 'sg-1', title: 'BezosMax Smart Audio Glasses', price: 200.00, description: 'BezosMax Smart Audio Glasses with Magnetic Clip-on Polarized Sunglasses offer a 2-in-1 design, allowing you to easily switch between optical glasses and sunglasses with snap-on magnetic lenses. Featuring built-in HiFi stereo speakers and smart touch controls, these glasses connect via Bluetooth for immersive audio and clear calls. The optical lenses block 98% of UV rays and reduce digital eye strain, while the open-ear design maintains environmental awareness. With up to 8 hours of battery life and fast type-C charging, they are ideal for everyday use, travel, and outdoor adventures.', image: '/images/aviators.jpg', category: 'sunglasses', stock: 18, trending: true, rating: 4.5, reviews: 24 },


  // Back to School
  { id: 'bs-1', title: 'Casio FX-82ZA Plus II Scientific Calculator (Black)', price: 395.00, originalPrice: 399.00, description: 'a battery-powered device made by Casio, featuring a durable plastic construction. This scientific calculator offers 283 functions, including GCD/LCM calculations, hour/minute/second conversions, data handling, regression analysis, and binary to decimal conversions. Its natural textbook 2-line display ensures easy reading and usability. Ideal for both students and professionals, the Casio FX-82ZA Plus II simplifies complex calculations with its user-friendly design and comprehensive capabilities.', image: '/images/casio-calc.jpg', category: 'back-to-school', stock: 12, trending: true, rating: 4.7, reviews: 36 },
  { id: 'bs-1', title: 'The HP 10bII+ Financial Calculator', price: 850.00, originalPrice: 860.00, description: 'a battery-powered business calculator from HP, featuring a compact black design and a 2-centimeter LCD display for clear viewing of calculations. Powered by two included lithium metal batteries, this calculator offers up to 12 digits of accuracy for precise results. With over 170 built-in functions covering finance, business, and statistics, it serves as a reliable tool for a wide range of mathematical and business calculations. Additionally, it can store up to 22 numbers in memory registers for convenient recall and use.', image: '/images/casio-calc.jpg', category: 'back-to-school', stock: 12, trending: true, rating: 4.7, reviews: 36 },
  { id: 'bs-2', title: 'Freedom Stationery 4 Quire A4 Counter Books 3-Piece Set', price: 164.00, description: 'includes three multicolor books, each with 384 pages and feint and margin ruling for neat, organized writing. Featuring durable cardboard covers and a convenient A4 size, these counter books are ideal for note-taking, journaling, or general everyday use at home, in the office, or on the go. This set provides ample supply to elevate your writing and organization needs.', image: '/images/notebook.jpg', category: 'back-to-school', stock: 25, rating: 4.4, reviews: 22 },
  { id: 'bs-3', title: 'Pens Assorted 20-Pack BIC Crystal Xtra Life', price: 162.00, description: 'The BIC Crystal Xtra Life Ballpoint Pen Box includes 20 blue pens featuring a lightweight plastic design and a comfortable hexagonal grip for added control. Renowned for smooth writing and vivid lines, these versatile pens are ideal for a variety of writing tasks at home, school, or the office. The BIC Crystal combines flexibility and durability, making it a reliable choice for everyday use.', image: '/images/pens.jpg', category: 'back-to-school', stock: 30, rating: 4.3, reviews: 18 },
  { id: 'bs-4', title: 'Highlighters 6-Pack Pastel Multicolour', price: 59.00, description: 'Brighten up your notes with this set of 6 pastel highlighter markers. Each chisel-tip marker delivers vivid, multicolour ink for clear highlighting and underlining, all neatly packed in a resealable case—perfect for students and anyone who wants organized, colourful documents.', image: '/images/highlighters.jpg', category: 'back-to-school', stock: 28, rating: 4.5, reviews: 15 },
  { id: 'bs-5', title: 'LANCI 2-Piece Fluffy Pencil Pouch Set', price: 199.00, description: 'Keep your stationery organized in style with the LANCI 2-Piece Fluffy Pencil Pouch Set. This set features two soft, plush pen bags in pastel rainbow and purple gradient designs, each with a roomy interior that fits up to 40 pens or pencils. With smooth zippers and cute pom-pom pendants, these portable cases are perfect for school, college, or on-the-go organization—making them a fun and practical gift for students and teens.', image: '/images/pencil-case.jpg', category: 'back-to-school', stock: 22, rating: 4.2, reviews: 12 },
  
// Celebrations
  { id: 'cb-1', title: 'Birthday Balloons Set Rose Gold Balloon Garland', price: 350.00, description: 'Create a stunning party backdrop with this Rose Gold Balloon Garland Kit. Featuring 129 premium latex balloons in nude pastel pink, metallic gold, matte white, and shimmering confetti, this kit is perfect for weddings, bridal showers, baby showers, birthdays, and more. Easy to assemble with included tape and glue dots, the set adds a touch of elegance and fun to any celebration, making your event truly memorable.', image: '/images/balloons.jpg', category: 'celebrations', stock: 20, trending: true, rating: 4.4, reviews: 19 },
  { id: 'cb-2', title: 'Graduation Sash Moutina Mexican for class 2026', price: 520.00, description: 'Celebrate your heritage and achievement with the Moutina Mexican Sash for Graduation 2026. This vibrant serape stole features bold, colorful patterns inspired by Mexican tradition, crafted from durable, wrinkle-resistant fabric for a polished look. Designed for the Class of 2026, it drapes comfortably over your gown, making it a meaningful accessory and a perfect gift to honor both academic success and cultural pride.', image: '/images/grad-sash.jpg', category: 'celebrations', stock: 15, rating: 4.5, reviews: 11 },
  { id: 'cb-3', title: 'Party Banner Kit', price: 159.00, description: 'Happy Birthday banner with decorations', image: '/images/party-banner.jpg', category: 'celebrations', stock: 18, rating: 4.3, reviews: 14 },
  { id: 'cb-4', title: '30pcs Graduation Photo Prop Set', price: 100.00, description: 'Black & Gold Photography Studio Decor, Includes 2026 Graduation Decorations, With Stick Props, Suitable For High School And College Graduation Party', image: '/images/photo-props.jpg', category: 'celebrations', stock: 25, rating: 4.2, reviews: 9 },
  
// Bicycles-DONE
  { id: 'bc-1', title: 'Minhaj Sport 26 Inch BMX Bicycle, Steel Frame, Yellow', price: 2240.00, description: 'Experience strength, comfort, and style with the Minhaj Sport 26 Inch BMX Bicycle. Built with a durable steel frame for exceptional impact resistance, this bike is designed for both teens and adults. The 26-inch wheels offer stability and smooth handling on city streets, recreational paths, or light off-road terrain. Enjoy a comfortable ride with an adjustable seat and easy-grip BMX handlebars that suit various heights. With a reliable braking system and a sturdy crank and pedal assembly, you get dependable stopping power and efficient pedaling for every ride. The sporty BMX look is perfect for school commutes, weekend adventures, and everyday use—making this a versatile choice for male and female riders alike.', image: '/images/mountain-bike.jpg', category: 'bicycles', stock: 4, trending: true, rating: 4.6, reviews: 8 },
  { id: 'bc-2', title: 'Perfect Dealz CubeStyle Full Suspension Mountain Bike', price: 4399.00, description: 'The Perfect Dealz CubeStyle Full Suspension Mountain Bike is designed for both adults and teens seeking adventure and versatility. Featuring a modern stereo imperfect cube frame, this bike delivers a sporty look while providing stable riding support. The 26-inch wheels and wide-tyre design enhance grip and balance, making it ideal for a range of terrain—including roads, gravel paths, and light off-road trails. With a durable frame constructed to withstand everyday riding, you can count on long-lasting performance and reliability. The 21-speed gear system gives you the flexibility to tackle hills and flat stretches alike. Enjoy a comfortable riding experience thanks to the thoughtfully designed geometry, which helps reduce strain during longer journeys. This mountain bike combines style, comfort, and rugged capability—perfect for those who want a reliable ride for both daily commutes and weekend adventures.', image: '/images/city-bike.jpg', category: 'bicycles', stock: 5, rating: 4.4, reviews: 6 },
  { id: 'bc-3', title: '26 Inch Fat Tire Bike 7 gear, Dual Disc Brake Front Suspension, Mountain Trail Bike', price: 5220.00, description: 'Take on any terrain with the 26 Inch Fat Tire Mountain Bike, built for adults and youth seeking adventure and reliability. This bike features a robust high-carbon steel frame that offers strength and durability, along with a shock-absorbing front suspension and thickened outer wall for superior comfort and impact resistance. The 26-inch wide tires (up to 4 inches) provide exceptional grip, anti-slip performance, and wear resistance, making this bike suitable for off-road trails, city streets, beaches, and even snow. Enjoy smooth gear transitions with the full 7-speed gearing kit and grip shifters for total control. Safety is prioritized with a dual disc brake system on both the front and rear wheels, ensuring short braking distances and immediate stopping power in emergencies. Ergonomically designed for comfort, wear resistance, and corrosion protection, this fat tire bike is the perfect choice for urban commuting, mountain trails, or outdoor fun in any condition.', image: '/images/bike-helmet.jpg', category: 'bicycles', stock: 12, rating: 4.5, reviews: 14 },

  // Shoes men
  { id: 'sh-2', title: 'Skyrocket Lite 2 Running Shoes Unisex', price: 1300.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-3', title: 'Flyer Lite 3 Running Shoes', price: 1150.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-4', title: 'FlexFocus Lite Modern Running Shoes Unisex', price: 1349.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-5', title: 'Retaliate 3 Running Shoes Unisex', price: 1549.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-6', title: 'Electrify NITRO™ 4 Running Shoes Men', price: 1589.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-7', title: 'Electrify NITRO™ 5 Running Shoes Unisex', price: 2249.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-2', title: 'FAST-Trac NITRO™ 4 Trail Running Shoes Men', price: 3349.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-5', title: 'BMW M Motorsport Drift Cat 11 Sneakers Unisex', price: 1950.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'McLAREN RACING Caven III Sneakers Unisex', price: 1649.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'BMW M MOTORSPORT RS Surge Sneakers Unisex', price: 3059.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'SOFTRIDE Cosmic Sneakers Unisex', price: 799.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Shuffle Downtown Sneakers Unisex', price: 1310.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Suede XL Leather Sneakers Unisex', price: 1999.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Solarflash III Indoor Sports Shoes', price: 1860.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Milenio Tech 2000 Sneakers Unisex', price: 1610.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Desierto v3 Boots', price: 1950.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Shuffle Downtown Mid Sneakers Unisex', price: 1459.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'PUMA Fade Sneakers Unisex', price: 2760.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Suede Classic Sneakers Unisex', price: 1940.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Homura OG+ Sneakers Unisex', price: 2550.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  // shoes women
  { id: 'sh-2', title: 'Velocity NITRO™ 4 Running Shoes Women', price: 3150.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-2', title: 'Magnify NITRO™ 3 Running Shoes Women', price: 2200.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-2', title: 'Dasher Lite Running Shoes Unisex', price: 1249.00, description: 'Lightweight running shoes, breathable mesh', image: '/images/running-shoes.jpg', category: 'shoes', stock: 10, rating: 4.6, reviews: 22 },
  { id: 'sh-3', title: 'White Rebound Femme Mid Sneakers', price: 1499.00, description: 'Casual slip-on canvas shoes', image: '/images/slipon-shoes.jpg', category: 'shoes', stock: 14, rating: 4.4, reviews: 17 },
    
  { id: 'sh-4', title: 'Fuel Tan Graphic Boots', price: 760.00, description: 'the Tan Graphic Boots by Fuel. Crafted from durable PU fabric in a classic tan shade, these boots offer both fashion and function. Their versatile design makes them perfect for pairing with a range of outfits, ensuring comfort and standout appeal for any occasion.', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Catch Soleil Ballerina Shoes Women', price: 1250.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Court Lally Skye Feline Sneakers Women', price: 1449.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Catch Soleil Ballerina Shoes Women', price: 1250.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'PUMA x ASTON MARTIN ARAMCO F1® TEAM Caven III Low Sneakers Unisex', price: 1600.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Anzarun 2 Lite SLIPTECH™ Sneakers Unisex', price: 1250.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'K-Moda Sneakers Women', price: 1449.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Jada Classic Sneakers Women', price: 799.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Style Bolero 2.0 Sneakers Women', price: 199.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Carina Mia Sneakers Women', price: 1549.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Shuffle Downtown Sneakers Unisex', price: 799.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'BasicBalleCutOutFeatherZAD', price: 729.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'SOFTRIDE Cosmic Sneakers Unisex', price: 2210.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  { id: 'sh-5', title: 'Caven III Sneakers Unisex', price: 1450.00, description: 'Waterproof hiking boots, outdoor', image: '/images/hiking-boots.jpg', category: 'shoes', stock: 8, rating: 4.5, reviews: 12 },
  
  
];

export const iconMap: Record<string, string> = {
  'LayoutGrid': 'LayoutGrid',
  'CookingPot': 'CookingPot',
  'Lightbulb': 'Lightbulb',
  'Sparkles': 'Sparkles',
  'Shirt': 'Shirt',
  'Palette': 'Palette',
  'PersonStanding': 'PersonStanding',
  'Gem': 'Gem',
  'Droplets': 'Droplets',
  'Wind': 'Wind',
  'HeartPulse': 'HeartPulse',
  'FlaskConical': 'FlaskConical',
  'BookOpen': 'BookOpen',
  'Gamepad2': 'Gamepad2',
  'Headphones': 'Headphones',
  'SprayCan': 'SprayCan',
  'Sticker': 'Sticker',
  'Hand': 'Hand',
  'Cloud': 'Cloud',
  'Sun': 'Sun',
  'Backpack': 'Backpack',
  'PartyPopper': 'PartyPopper',
  'Bike': 'Bike',
  'Footprints': 'Footprints',
};

export const BANK_DETAILS = {
  bank: 'Capitec',
  accountName: 'MR Ragedi NG',
  accountNumber: '2081845985',
  branchCode: '470010',
  payshapNumber: '0631917709',
};

export const DELIVERY_DAYS_MIN = 1;
export const DELIVERY_DAYS_MAX = 8;
export const FREE_DELIVERY_THRESHOLD = 150;
export const LOWER_CAMPUS_FEE = 20;
export const UPPER_CAMPUS_FEE = 25;

export function getDeliveryFee(subtotal: number, location: 'lower' | 'upper'): number {
  if (subtotal >= FREE_DELIVERY_THRESHOLD) return 0;
  return location === 'upper' ? UPPER_CAMPUS_FEE : LOWER_CAMPUS_FEE;
}

export function getDeliveryLabel(location: 'lower' | 'upper'): string {
  return location === 'upper' ? 'Upper Campus' : 'Lower Campus';
}

export function generateOrderId(): string {
  return `YAF-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
}

export function isPasswordStrong(password: string): boolean {
  if (password.length < 8) return false;
  const hasNumber = /\d/.test(password);
  const hasLetter = /[a-zA-Z]/.test(password);
  const hasSpecial = /[!@#$%^&*(),.?":{}|<>]/.test(password);
  const isSequential = /^(12345678|abcdefgh|password|qwertyui)$/i.test(password);
  return hasNumber && hasLetter && hasSpecial && !isSequential;
}

export function generateRecoveryCode(): string {
  const digits = Math.floor(100 + Math.random() * 900).toString();
  const letters = String.fromCharCode(65 + Math.floor(Math.random() * 26)) + 
                  String.fromCharCode(65 + Math.floor(Math.random() * 26));
  return digits + letters;
}

export const STATUS_STEPS = [
  { id: 'order_received', label: 'Order Received', description: 'We have received your order and are preparing it.' },
  { id: 'shipped', label: 'Order Shipped', description: 'Your order has been shipped from our warehouse.' },
  { id: 'arrived_storage', label: 'At Storage Facility', description: 'Your order has arrived at Grahamstown storage facility.' },
  { id: 'out_for_delivery', label: 'Out for Delivery', description: 'Your order will be delivered today.' },
  { id: 'ready_for_pickup', label: 'Ready for Collection', description: 'Young Agripreneurs Store has your order ready.' },
  { id: 'driver_nearby', label: 'Driver Nearby', description: 'Driver is around campus, please come and get your order.' },
  { id: 'delivered', label: 'Delivered', description: 'Order delivered successfully!' },
];
